### ISSUE TITLE
Add Long/Lat coordinates to the map popup

### ISSUE THREAD

**Issue by robert-waterman** [Esri/wayback#88]
This feature should allow users to see and copy the coordinates for a location of interest.

**Comment by robert-waterman** [comment]
- Coordinates should be labeled X:dd Y:dd in decimal degrees to at least 4 decimal places
- Single click copy should be enabled as dd space delimited coordinates without the labels (easily paste into map location search without editing)

**Comment by vannizhang** [comment]
We should display the coordinates in this format: `Lat: xxx Lon: xxx`

**Comment by vannizhang** [comment]
@robert-waterman pushed this enhancement to PROD.
