### ISSUE TITLE
Download Tile Package: Min tile package level should always be 12 by default

### ISSUE THREAD

**Issue by robert-waterman** [Esri/wayback#90]
I believe the current functionality sets the min level based on my current zoom level. The users map view should only control the bounding box, and not the min/max levels.

In the screenshot below, the min level should be 12 and the max 21 for each job.

![image](https://github.com/vannizhang/wayback/assets/40008490/4a827401-1da9-4351-8031-bca678b472b3)

**Comment by vannizhang** [comment]
reopen this issue per request from @robert-waterman. We will need to either lose up or remove the restriction on the Min tile package level.

**Comment by vannizhang** [comment]
@robert-waterman pushed this fix to PROD.
